  import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import 'rsuite/dist/rsuite-no-reset.min.css';
  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased min-h-screen`}>
        <div className="fixed inset-0 -z-10">
          <div 
            className="absolute inset-0 bg-cover bg-center bg-no-repeat"
            style={{
              backgroundImage: 'url(https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80)',
              filter: 'blur(4px)',
              transform: 'scale(1.1)',
            }}
          />
          <div className="absolute inset-0 bg-black/20" />
        </div>
        <div className="relative z-10">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
